Gitsplit\ConnectBundle\Entity\Authorization:
    type: entity
    repositoryClass: Gitsplit\ConnectBundle\Repository\AuthorizationRepository
    table: authorization
    indexes:
        resourceowner_username_idx:
            columns:
                - resourceowner_name
                - username
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        resourceOwnerName:
            column: resourceowner_name
            type: string
        username:
            column: username
            type: string
        authorizationToken:
            column: authorization_token
            type: string
        clientId:
            column: client_id
            type: string
            nullable: false
        clientSecret:
            column: client_secret
            type: string
            nullable: false
        expirationDate:
            column: expiration_date
            type: datetime

    oneToOne:
        user:
            targetEntity: Gitsplit\UserBundle\Entity\User
            inversedBy: authorization
            joinColumn:
                name: user_id
                referencedColumnName: id
