hwi_oauth:
    firewall_name: secured_area
    resource_owners:
        github:
            type: github
            client_id: %oauth_github_id%
            client_secret: %oauth_github_secret%
            scope: "admin:repo_hook"