hwi_oauth:
    firewall_name: secured_area
    resource_owners:
        github:
            type: github
            client_id: %oauth.github.id%
            client_secret: %oauth.github.secret%
            scope: "admin:repo_hook"