security:
    providers:
        customer:
            entity:
                class: Gitsplit\UserBundle\Entity\User
                property: email

    firewalls:
        dev:
            #context: admin_context
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            context: secured_context
            pattern: ^/.*
            anonymous: true
            security: true
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   logout
                target: homepage
                invalidate_session: false
            oauth:
                login_path: /login
                use_forward: false
                failure_path: /login
                oauth_user_provider:
                    service: gitsplit.oauth_provider
                resource_owners:
                    github: /login/check-github
        login_area:
            pattern: ^/login$
            anonymous: true

    access_control:
        push_area:
            path: ^/push.*
            roles: IS_AUTHENTICATED_ANONYMOUSLY

        login_area:
            path: ^/login.*
            roles: IS_AUTHENTICATED_ANONYMOUSLY

        user_area:
            path: ^.*
            roles: ROLE_USER