services:

    #
    # Object Managers
    #
    gitsplit.object_manager.user:
        class: Doctrine\Common\Persistence\ObjectManager
        factory_service: elcodi.manager_provider
        factory_method: getManagerByEntityNamespace
        arguments:
            - Gitsplit\UserBundle\Entity\User
