services:

    #
    # Object Managers
    #
    gitsplit.object_manager.suite:
        class: Doctrine\Common\Persistence\ObjectManager
        factory_service: elcodi.manager_provider
        factory_method: getManagerByEntityNamespace
        arguments:
            - Gitsplit\EngineBundle\Entity\Suite

    gitsplit.object_manager.work:
        class: Doctrine\Common\Persistence\ObjectManager
        factory_service: elcodi.manager_provider
        factory_method: getManagerByEntityNamespace
        arguments:
            - Gitsplit\EngineBundle\Entity\Work
