services:

    #
    # Repositories
    #
    gitsplit.repository.suite:
        class: Gitsplit\EngineBundle\Repository\SuiteRepository
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: Gitsplit\EngineBundle\Entity\Suite

    gitsplit.repository.work:
        class: Gitsplit\EngineBundle\Repository\WorkRepository
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: Gitsplit\EngineBundle\Entity\Work
