Gitsplit\EngineBundle\Entity\Work:
    type: entity
    repositoryClass: Gitsplit\EngineBundle\Repository\WorkRepository
    table: work
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        path:
            column: path
            type: string
            nullable: false
        remote:
            column: remote
            type: string
            nullable: false
        log:
            column: log
            type: text
            nullable: false
        status:
            column: status
            type: integer
            nullable: false
        result:
            column: result
            type: integer
            nullable: true
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime

    manyToOne:
        suite:
            targetEntity: Gitsplit\EngineBundle\Entity\Suite
            inversedBy: works
            joinColumn:
                name: suite_id
                referencedColumnName: id
                nullable: false
                onDelete: "CASCADE"
                onUpdate: "CASCADE"

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]
