services:

    #
    # Event Listeners
    #
    gitsplit.event_listener.repository_hook:
        class: Gitsplit\RepositoryBundle\EventListener\RepositoryHookEventListener
        arguments:
            - @service_container
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preRemove }
