services:

    #
    # Repositories
    #
    gitsplit.repository.repository:
        class: Gitsplit\RepositoryBundle\Repository\RepositoryRepository
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: Gitsplit\RepositoryBundle\Entity\Repository
